name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Display Node and npm version
      run: |
        node --version
        npm --version
    - name: Install dependencies
      run: |
        cd api
        npm ci
    - name: Run tests
      run: cd api && npm test